### ISSUE TITLE
how do i use this? Instruction not very clear. 

### ISSUE THREAD

**Issue by KeepCreatingOnline** [DarkTrick/htmlfilemerger#10]

**Comment by DarkTrick** [comment]
- Download to some location (e.g. `Desktop/htmlfilemerger`)
- open `Desktop/htmlfilemerger/src` in terminal
- run `python3 htmlmerger inputfile`

**Comment by KeepCreatingOnline** [comment]
> 

Im getting the error "FATAL ERROR: file `inputfile` could not be accessed."

**Comment by DarkTrick** [comment]
Perhaps you don't have access to the file you are trying to access.
