### ISSUE TITLE
doesnt handle remote resources??

### ISSUE THREAD

**Issue by zachgrayio** [DarkTrick/htmlfilemerger#11]
```
python3 htmlmerger mypath/index.html
Problems occured
  Error: Line 34: Could not find file `https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css`; searched in `mypath/https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css`.
```

unfortunately this is entirely unusable if it cant just copypasta over the links to remote files that it finds, cant really think of a single case where there's not going to be a few items pulled off a CDN in really any real HTML page crafted after 2002

**Comment by DarkTrick** [comment]
Thanks for reporting!

My experience:
I use Firefox, when I safe the website offline all these resources are grabbed and saved to disk, and the links are transformed to local paths.

Questions:
(1) What browser are you using?
(2) Can you provide a specific web site that had this problem?

Feel free to reopen upon interaction.

**Comment by DarkTrick** [comment]
feel free to reopen
